apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopswebapp
  labels:
    app: devopswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopswebapp
  template:
    metadata:
      labels:
        app: devopswebapp
    spec:
      containers:
        - name: devopswebapp
          image: nanmycontreg.azurecr.io/devopswebapp
          imagePullPolicy: Always
